version: "3.8"

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
    command: poetry run uvicorn --port 8000 --host 0.0.0.0 --reload main:app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1
    ports:
      - "5437:5432"
    env_file:
      - .env.postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data