"""namespace_constrain

Revision ID: b8184ebd2ae4
Revises: 4a5b314e888e
Create Date: 2022-12-22 20:15:37.436450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8184ebd2ae4'
down_revision = '4a5b314e888e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_namespace_role_constraint', 'user_namespace', ['user_id', 'namespace_id', 'role_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_namespace_role_constraint', 'user_namespace', type_='unique')
    # ### end Alembic commands ###
