"""add_item_and_movement

Revision ID: 4a5b314e888e
Revises: 699b3e4cfb7a
Create Date: 2022-12-17 14:02:50.058724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5b314e888e'
down_revision = '699b3e4cfb7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=511), nullable=False),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.Column('type', sa.Enum('OBJECT', 'STORAGE', name='itemtypeenum'), nullable=False),
    sa.Column('count', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unit', sa.Enum('PCS', 'KGS', name='itemunitenum'), nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=3000), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_item_id', sa.Integer(), nullable=True),
    sa.Column('to_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_movement')
    op.drop_table('item_image')
    op.drop_table('item')
    # ### end Alembic commands ###
